---
- hosts: all
  gather_facts: no
  tasks:
    - set_stats:
        data:
          repo_path: "{{ playbook_dir }}"
  
    #- set_fact:
    #    repo_path2: "{{ playbook_dir }}"

    #- debug:
    #    msg: "{{ playbook_dir }}"
  
    #- debug:
    #    msg: "{{ repo_path2 }}"
  
    #- debug:
    #    msg: "{{ repo_path }}"
  
    - name: file update
      local_action: "shell cd {{ playbook_dir }} ; git checkout {{ git_tag }}"
      when: switch_flag is defined
      
    - name: copy hosts 
      copy:
        src: "{{ playbook_dir }}/files/hosts"
        dest: /etc/hosts
