---
- hosts: all
  gather_facts: no
  tasks:
    - set_stats:
        data:
          repo_path: "{{ playbook_dir }}"
  
    - name: file update
      local_action: "shell cd {{ playbook_dir }} ; git checkout {{ git_tag }}"
      when: switch_flag is defined
      
    - fail:
      msg: "The system may not be provisioned according to the CMDB status."

    - name: copy hosts 
      copy:
        src: "{{ playbook_dir }}/files/hosts"
        dest: /etc/hosts
