---
- name: switch back of tag
  hosts: all
  gather_facts: no
  tasks:
    # 切り戻しに指定したtagのブランチを作成
    - shell: "git checkout -b {{ git_tag }} {{ git_tag }}"
      args:
        #chdir: "{{ repo_path }}"
        chdir: "{{ playbook_dir }}"

    # `switch_flag` を定義
    - set_stats:
        data:
          switch_flag: 1
